id = "clojure"
name = "Clojure"
description = "Clojure support."
version = "0.3.0"
schema_version = 1
authors = ["Paulo Roberto de Oliveira Castro <p.oliveira.castro@gmail.com>"]
repository = "https://github.com/zed-extensions/clojure"

[language_servers.clojure-lsp]
name = "clojure-lsp"
language = "Clojure"

[grammars.clojure]
repository = "https://github.com/sogaiu/tree-sitter-clojure"
commit = "e43eff80d17cf34852dcd92ca5e6986d23a7040f"
